title: <p align="center"> Nguyen Ngoc Truong Chinh </p>

logo: "/images/avt.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a >LinkedIn</a> |
  <a href="https://github.com/truongchinh1211">GitHub</a>
  </p>
  
  <p align="justify">
  "I am a Computer Science student at SGU University with a passion for becoming a Web Development Engineer.
  <br><br>
   I'm currently exploring new technologies and frameworks to build modern web tools. My goal is to contribute to the software industry's progress by staying updated on trends and advancements.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
